# Generated by Django 5.2.6 on 2025-12-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='job_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
